Thread #x was created
   at 0x........: clone (in /...libc...)
   by 0x........: do_clone (in /lib/libpthread...)
   by 0x........: pthread_create@GLIBC_ (in /lib/libpthread...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: barriers_and_races (pth_barrier.c:84)
   by 0x........: main (pth_barrier.c:107)

Thread #x was created
   at 0x........: clone (in /...libc...)
   by 0x........: do_clone (in /lib/libpthread...)
   by 0x........: pthread_create@GLIBC_ (in /lib/libpthread...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: barriers_and_races (pth_barrier.c:84)
   by 0x........: main (pth_barrier.c:107)

Possible data race during write of size 4 at 0x........ by thread #x
   at 0x........: threadfunc (pth_barrier.c:57)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   by 0x........: start_thread (in /lib/libpthread...)
   by 0x........: clone (in /...libc...)
 This conflicts with a previous write of size 4 by thread #x
   at 0x........: threadfunc (pth_barrier.c:57)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   by 0x........: start_thread (in /lib/libpthread...)
   by 0x........: clone (in /...libc...)
